[build-system]
requires = [ "setuptools>=70.0", "wheel",]
build-backend = "setuptools.build_meta"

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
follow_imports = "skip"
exclude = [ "^cattino/third_party/.*",]

[tool.pyright]
exclude = [ "^cattino/third_party/.*",]

